apiVersion: v1
kind: PersistentVolume
metadata:
  name: http-pv
  labels:
    app: webapp
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sda1/data/http/"

